# Generated by Django 4.2.1 on 2023-05-15 05:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('razon_soc', models.CharField(max_length=255, null=True)),
                ('dni', models.CharField(max_length=8)),
                ('email', models.EmailField(max_length=255, null=True, validators=[django.core.validators.EmailValidator(message='Ingrese una dirección de email válida.')])),
                ('tel', models.CharField(max_length=255, null=True)),
                ('domicilio', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('marca', models.CharField(max_length=255, null=True)),
                ('precio', models.FloatField()),
                ('stock_actual', models.IntegerField()),
                ('proveedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='compra.proveedor')),
            ],
        ),
    ]
